//! -----------------images-----------------
const avatar = "assets/images/avatar.png";
const onBoarding = "assets/images/onboarding.png";
const newWork = "assets/images/new-york.png";
const japan = "assets/images/japan.png";
const apartment = "assets/images/apartment.png";
const apartment2 = "assets/images/apartment2.png";
// const avatar = "assets/images/avatar.png";
// const avatar = "assets/images/avatar.png";
// const avatar = "assets/images/avatar.png";
// const avatar = "assets/images/avatar.png";
//! -----------icons-------------------------
const calendar = "assets/icons/calendar.png"; //? profile
const info = "assets/icons/info.png";
const back = "assets/icons/back-arrow.png";
const language = "assets/icons/language.png";
const bell = "assets/icons/bell.png";
const peoples = "assets/icons/people.png";
const share = "assets/icons/send.png";
const security = "assets/icons/shield.png";
const wallet = "assets/icons/wallet.png";
const search = "assets/icons/search.png"; //? nav bar
const selectedSearch = "assets/icons/selected_Search.png";
const person = "assets/icons/person.png";
const selectedProfile = "assets/icons/Selected_Profile.png";
const selectedHome = "assets/icons/home.png";
const home = "assets/icons/Selected_home.png";
const filter = "assets/icons/filter.png";
const area = "assets/icons/area.png";
const bath = "assets/icons/bath.png";
const bed = "assets/icons/bed.png";
const park = "assets/icons/car-park.png";
const restaurants = "assets/icons/cutlery.png";
const pet = "assets/icons/dog.png";
const gym = "assets/icons/dumbell.png";
const location = "assets/icons/location.png";
const phone = "assets/icons/phone.png";
const run = "assets/icons/run.png";
const swim = "assets/icons/swim.png";
const wifi = "assets/icons/wifi.png";
const heart = "assets/icons/heart.png";
const logOut = "assets/icons/logout.png";
const google = "assets/icons/google.png";
const star = "assets/icons/star.png";
const paypal = "assets/icons/Paypal.png";
const masterCard = "assets/icons/MasterCard.png";
const googlePay = "assets/icons/GooglePay.png";
const chip = "assets/icons/Chip.png";
//!-----------animations----------------------
const easyRent = "assets/animations/EeasyRent.json";
